name: Repo Library - Manual Push
on: [workflow_dispatch]
jobs:
  publish:
    name: Publish Repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Repo Integration Test
        run: dotnet test Example.Service.Integration/Example.Service.Integration.csproj
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: EF.Turbo.Service/EF.Turbo.Service.csproj # Relative to repository root
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: efTurbo-v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key